name: '0003 - Control Plane'
 
on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain you're targeting for deployment."
        type: choice
        required: true
        options:
        - accounts
        - kiwisaver
 
jobs:
  dev:
    name: 'dev'
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_BLOB_STORAGE_ACCESS_KEY }}
      ASTRA_ORG_API_TOKEN: ${{secrets.ASTRA_ORG_API_TOKEN}}
      ASTRA_ORG_ID: ${{vars.ASTRA_ORG_ID}}
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: controlplane/${{ github.event.inputs.domain }}/dev
 
    steps:
    - uses: hashicorp/setup-terraform@v2
    
    # Checkout the repository to the GitHub Actions runner
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: Astra CLI - Install
      continue-on-error: true
      run: curl -Ls "https://dtsx.io/get-astra-cli" | bash
        
    - name: Astra CLI - Setup
      run: /home/runner/.astra/cli/astra setup --token $ASTRA_ORG_API_TOKEN
    
    - name: Get Database Id
      run: |
        db_id=$(/home/runner/.astra/cli/astra db get ${{ github.event.inputs.domain }} --key id)
        echo "ASTRA_DB_ID=$db_id" >> "$GITHUB_ENV"

    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: terraform init
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -var token=${{ secrets.ASTRA_ORG_API_TOKEN }} -var environment=dev -var astradbid=$ASTRA_DB_ID -var organisationid=$ASTRA_ORG_ID -var astradbid=$ASTRA_DB_ID
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var token=${{ secrets.ASTRA_ORG_API_TOKEN }} -var environment=dev -var astradbid=$ASTRA_DB_ID -var organisationid=$ASTRA_ORG_ID -var astradbid=$ASTRA_DB_ID
