name: 0005 - Token Rotation

on:
  workflow_dispatch:
  #schedule:
    #- cron: '* * * * *' # Every Minute

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Move to astradb.terraform folder
        run: cd astradb.terraform

      - name: 'Terraform Format'
        id: format
        run: terraform fmt
         
      - name: 'Terraform Init'
        id: init
        run: >
         terraform init -backend-config=backend_dev.conf
 
      - name: 'Terraform Validate'
        id: validate
        run: terraform validate

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan
