name: 0006 - Token Rotation

on:
  workflow_dispatch:
  #schedule:
    #- cron: '* * * * *' # Every Minute

jobs:
  approval:
    name: approval
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ninocinco, ncinco
      - name: approval
        run: echo checking approval

  build:
    env:
      ASTRA_ORG_API_TOKEN: ${{secrets.ASTRA_ORG_API_TOKEN}}
      ARM_ACCESS_KEY: ${{ secrets.AZURE_BLOB_STORAGE_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.MVP_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SKIP_PROVIDER_REGISTRATION: true
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
    needs: approval
    defaults:
      run:
        shell: bash
        working-directory: token_rotation

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Terraform Format'
        id: format
        run: terraform fmt
         
      - name: 'Terraform Init'
        id: init
        run: terraform init
 
      - name: 'Terraform Validate'
        id: validate
        run: terraform validate

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -var token=$ASTRA_ORG_API_TOKEN -var azure_client_id=$ARM_CLIENT_ID -var azure_tenant_id=$ARM_TENANT_ID -var azure_client_secret=$ARM_CLIENT_SECRET
        
      - name: 'Terraform Apply'
        id: apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var token=$ASTRA_ORG_API_TOKEN -var azure_client_id=$ARM_CLIENT_ID -var azure_tenant_id=$ARM_TENANT_ID -var azure_client_secret=$ARM_CLIENT_SECRET
