name: AstraDB - Sensitive Data

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain you're targeting for deployment."
        type: choice
        required: true
        options:
        - accounts
        - kiwisaver
        - loans
      account_name:
        description: "Account name of the storage account."
        required: true
      container_name:
        description: "Container name on storage account where the file is located."
        required: true
      path_name:
        description: "Path name on container."
        required: true
      access_key:
        description: "Access key of the storage account."
        required: true

jobs:
  Dev:
    name: "Dev"
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_API_TOKEN }}
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.event.inputs.domain }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Download from blob storage
        run: az storage blob download \
          --account-name ${{ github.event.inputs.account_name }} \
          --container-name ${{ github.event.inputs.container_name }} \
          --name ${{ github.event.inputs.path_name }} \
          --file ${{ github.event.inputs.path_name }} \
          --account-key ${{ github.event.inputs.access_key }} \
          --auth-mode key
      
      - name: Install DSBulk
        run: |
          curl -OL https://downloads.datastax.com/dsbulk/dsbulk-1.10.tar.gz
          tar -xzvf dsbulk-1.10.tar.gz
      
      - name: Run Data Scripts
        run: echo ${{ github.event.inputs.access_key }}
