name: 'AstraDB - Control Plane'
 
on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain you're targeting for deployment."
        type: choice
        required: true
        options:
        - accounts
        - kiwisaver
        - loans
 
jobs:
  dev:
    name: 'dev'
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_BLOB_STORAGE_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: dev
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/servicedomains/${{ github.event.inputs.domain }}
 
    steps:
    - uses: hashicorp/setup-terraform@v2
    
    # Checkout the repository to the GitHub Actions runner
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: >
       terraform init \
         -backend-config="resource_group_name=Terraform_State" \
         -backend-config="storage_account_name=astradbstate" \
         -backend-config="container_name=${{ github.event.inputs.domain }}" \
         -backend-config="key=${environment}"
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Get'
      id: get
      run: terraform get

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -var token=${{ secrets.ASTRA_API_TOKEN }} -var environment=dev
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var token=${{ secrets.ASTRA_API_TOKEN }} -var environment=dev

  uat:
    name: 'uat'
    needs: dev
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_BLOB_STORAGE_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: uat
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/servicedomains/${{ github.event.inputs.domain }}
 
    steps:
    - uses: hashicorp/setup-terraform@v2
    
    # Checkout the repository to the GitHub Actions runner
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: terraform init -backend-config=backend_uat.conf
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Get'
      id: get
      run: terraform get

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -var token=${{ secrets.ASTRA_API_TOKEN }} -var environment=uat
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var token=${{ secrets.ASTRA_API_TOKEN }} -var environment=uat

  prod:
    name: 'prod'
    needs: uat
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_BLOB_STORAGE_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: prod
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/servicedomains/${{ github.event.inputs.domain }}
 
    steps:
    - uses: hashicorp/setup-terraform@v2
    
    # Checkout the repository to the GitHub Actions runner
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: terraform init -backend-config=backend_prod.conf
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Get'
      id: get
      run: terraform get

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -var token=${{ secrets.ASTRA_API_TOKEN }} -var environment=prod
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var token=${{ secrets.ASTRA_API_TOKEN }} -var environment=prod
