name: AstraDB - Data Plane

on:
  workflow_dispatch:

jobs:
  Astra-CLI:
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{secrets.ASTRA_API_TOKEN}}
      ASTRA_DB_NAME: ninodbcli
      ASTRA_DB_KEYSPACE: ninokp
      TERM: linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Astra CLI
        run: curl -Ls "https://dtsx.io/get-astra-cli" | bash
        
      - name: Astra CLI - Setup
        run: /home/runner/.astra/cli/astra setup --token $ASTRA_DB_APPLICATION_TOKEN

      - name: Create DB
        if: always()
        run: /home/runner/.astra/cli/astra db create $ASTRA_DB_NAME -k $ASTRA_DB_KEYSPACE --token $ASTRA_DB_APPLICATION_TOKEN --if-not-exists
