name: Astra CLI

on: push

jobs:
  Astra-CLI:
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{secrets.ASTRA_API_TOKEN}}
      TERM: linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Install Astra CLI
        run: |
          curl -Ls "https://dtsx.io/get-astra-cli" | bash
          astra setup
          astra db list
