name: CasDB

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: curl -Ls "https://dtsx.io/get-astra-cli" | bash
      - run: astra setup
      - run: astra db list
