name: CasDB

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: pip install -U cqlsh
      - run: docker pull cassandra
      - run: docker run --rm -p 9042:9042 cassandra
      - run: cqlsh
