name: CasDB

on: push

env:
  CARGO_TERM_COLOR: always


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes: 
           - ${{ github.workspace }}:/workspace
    steps:
      - uses: actions/checkout@v2
      - run: docker exec -i ${{ job.services.cassandra.id }} cqlsh -f /workspace/setup.cql
