name: 'Database Deployment'
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment you're targetting for deployment."
        type: choice
        required: true
        default: dev
        options:
        - dev
        - uat
        - prod
      domain:
        description: "Domain you're targetting for deployment."
        type: choice
        required: true
        options:
        - accounts
        - kiwisaver
        - loans
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_BLOB_STORAGE_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: dev
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.event.inputs.domain }}
 
    steps:
    - uses: hashicorp/setup-terraform@v2
    
    # Checkout the repository to the GitHub Actions runner
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: terraform init      
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate
         
    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -var token=${{ secrets.ASTRA_API_TOKEN }}
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var token=${{ secrets.ASTRA_API_TOKEN }}
