name: Setup Cassandra

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/setup-cassandra-action@v1.0.0
        with:
          host: '192.13.131.0'
          port: 9042
          username: ${{ secrets.CASSANDRA_USERNAME }}
          password: ${{ secrets.CASSANDRA_PASSWORD }}
          connect-timeout: 30
          keyspace: test
          scripts_path: './scripts'
