name: 'test test'
 
on:
  workflow_dispatch:
  push:
    paths:
      - 'servicedomains/**'

jobs:
  dev:
    name: "dev"
    env:
      ASTRA_DB_API_TOKEN: ${{secrets.ASTRA_API_TOKEN}}
      ASTRA_DB_ID: ""
      ASTRA_ORG_API_TOKEN: ${{secrets.ASTRA_ORG_API_TOKEN}}
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
