name: 'xxxx - test'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain you're targeting for deployment."
        type: choice
        required: true
        options:
        - accounts
        - kiwisaver

jobs:
  dev:
    name: "dev"
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{secrets.ASTRA_API_TOKEN}}
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: dataplane/${{ github.event.inputs.domain }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Astra CLI
        continue-on-error: true
        run: curl -Ls "https://dtsx.io/get-astra-cli" | bash
        
      - name: Setup
        run: /home/runner/.astra/cli/astra setup --token $ASTRA_DB_APPLICATION_TOKEN
        
      - name: Run Schema Scripts
        run: |
          cd 1000_schema
          for f in *.cql; do
            echo "checking if file '${f}' was executed before...."
            cql_statement="SELECT count(*) FROM kiwisaver.executed_scripts WHERE folder='${{ github.event.inputs.domain }}/1000_schema' AND script_name='${f}'"
            echo "Select Statement: ${cql_statement}"
            was_executed=$(/home/runner/.astra/cli/astra db cqlsh kiwisaver -e "${cql_statement}")
            echo "was file '${f}' executed before: ${was_executed}"
          done;
          
          cd 2000_data
          for f in *.cql; do
            echo "checking if file '${f}' was executed before...."
            cql_statement="SELECT count(*) FROM kiwisaver.executed_scripts WHERE folder='${{ github.event.inputs.domain }}/2000_data' AND script_name='${f}'"
            echo "Select Statement: ${cql_statement}"
            was_executed=$(/home/runner/.astra/cli/astra db cqlsh kiwisaver -e "${cql_statement}")
            echo "was file '${f}' executed before: ${was_executed}"
          done;
