name: 'xxxx - test'

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain you're targeting for deployment."
        type: choice
        required: true
        options:
        - accounts
        - kiwisaver

jobs:
  dev:
    name: "dev"
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{secrets.ASTRA_API_TOKEN}}
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: dataplane/${{ github.event.inputs.domain }}/1000_schema

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Astra CLI
        continue-on-error: true
        run: curl -Ls "https://dtsx.io/get-astra-cli" | bash
        
      - name: Setup
        run: /home/runner/.astra/cli/astra setup --token $ASTRA_DB_APPLICATION_TOKEN
        
      - name: Run Schema Scripts
        run: |
          for f in *.cql; do
            echo "checking if file '${f}' was executed before...."
            
            /home/runner/.astra/cli/astra db cqlsh kiwisaver -e "SELECT * FROM kiwisaver.executed_scripts"
          done;
