INSERT INTO kiwisaver.ninotable (id, first_name, last_name) VALUES (5b2f1af1-812b-4904-8d9f-ce9fb65765f7, 'first_name_01', 'last_name_01');
INSERT INTO kiwisaver.ninotable (id, first_name, last_name) VALUES (b9697f0a-89db-4300-a402-f03faa5dcf0a, 'first_name_02', 'last_name_02');
INSERT INTO kiwisaver.ninotable (id, first_name, last_name) VALUES (d6c554a8-92ee-401f-bdd9-1c3778915b17, 'first_name_03', 'last_name_03');
INSERT INTO kiwisaver.ninotable (id, first_name, last_name) VALUES (8b84e1fa-1dfe-42dc-8844-592238f03b92, 'first_name_04', 'last_name_04');
INSERT INTO kiwisaver.ninotable (id, first_name, last_name) VALUES (e4fe89f7-5627-4100-b4b3-db86483d8f28, 'first_name_05', 'last_name_05');
INSERT INTO kiwisaver.ninotable (id, first_name, last_name) VALUES (e4fe89f7-5627-4100-b4b3-db86483d8f21, 'first_name_11', 'last_name_11');

